# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keywee.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keywee.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0ckeywee.proto\x12\x02pb\"\x84\x01\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x16\n\x0e\x65stimate_ready\x18\x03 \x01(\x08\x12\x15\n\raudiance_size\x18\x04 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\r\n\x05title\x18\x06 \x01(\t\x12\x14\n\x0cintroduction\x18\x07 \x01(\t\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2d\n\x03\x41PI\x12\x1d\n\x03\x41\x64\x64\x12\x08.pb.Item\x1a\n.pb.Status\"\x00\x12\x1c\n\x04Read\x12\x08.pb.Item\x1a\x08.pb.Item\"\x00\x12 \n\x05Index\x12\t.pb.Empty\x1a\x08.pb.Item\"\x00\x30\x01\x62\x06proto3')
)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='pb.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.Item.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='pb.Item.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimate_ready', full_name='pb.Item.estimate_ready', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audiance_size', full_name='pb.Item.audiance_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pb.Item.content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='pb.Item.title', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='introduction', full_name='pb.Item.introduction', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=153,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='pb.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.Status.code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='pb.Status.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=194,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='pb.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'keywee_pb2'
  # @@protoc_insertion_point(class_scope:pb.Item)
  ))
_sym_db.RegisterMessage(Item)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'keywee_pb2'
  # @@protoc_insertion_point(class_scope:pb.Status)
  ))
_sym_db.RegisterMessage(Status)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'keywee_pb2'
  # @@protoc_insertion_point(class_scope:pb.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_API = _descriptor.ServiceDescriptor(
  name='API',
  full_name='pb.API',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=205,
  serialized_end=305,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='pb.API.Add',
    index=0,
    containing_service=None,
    input_type=_ITEM,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='pb.API.Read',
    index=1,
    containing_service=None,
    input_type=_ITEM,
    output_type=_ITEM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Index',
    full_name='pb.API.Index',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ITEM,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['API'] = _API

# @@protoc_insertion_point(module_scope)
