// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keywee.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url                  string             `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	EstimateReady        bool               `protobuf:"varint,3,opt,name=estimate_ready,json=estimateReady" json:"estimate_ready,omitempty"`
	AudianceSize         int64              `protobuf:"varint,4,opt,name=audiance_size,json=audianceSize" json:"audiance_size,omitempty"`
	Content              string             `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Title                string             `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	Introduction         string             `protobuf:"bytes,7,opt,name=introduction" json:"introduction,omitempty"`
	Geo                  []string           `protobuf:"bytes,8,rep,name=geo" json:"geo,omitempty"`
	Topics               []string           `protobuf:"bytes,9,rep,name=topics" json:"topics,omitempty"`
	FacebookIntrests     []*FacebookIntrest `protobuf:"bytes,10,rep,name=facebook_intrests,json=facebookIntrests" json:"facebook_intrests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_keywee_5568685640413dc2, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetEstimateReady() bool {
	if m != nil {
		return m.EstimateReady
	}
	return false
}

func (m *Item) GetAudianceSize() int64 {
	if m != nil {
		return m.AudianceSize
	}
	return 0
}

func (m *Item) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Item) GetGeo() []string {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Item) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Item) GetFacebookIntrests() []*FacebookIntrest {
	if m != nil {
		return m.FacebookIntrests
	}
	return nil
}

type Status struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_keywee_5568685640413dc2, []int{1}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_keywee_5568685640413dc2, []int{2}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type FacebookIntrest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FacebookIntrest) Reset()         { *m = FacebookIntrest{} }
func (m *FacebookIntrest) String() string { return proto.CompactTextString(m) }
func (*FacebookIntrest) ProtoMessage()    {}
func (*FacebookIntrest) Descriptor() ([]byte, []int) {
	return fileDescriptor_keywee_5568685640413dc2, []int{3}
}
func (m *FacebookIntrest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FacebookIntrest.Unmarshal(m, b)
}
func (m *FacebookIntrest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FacebookIntrest.Marshal(b, m, deterministic)
}
func (dst *FacebookIntrest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FacebookIntrest.Merge(dst, src)
}
func (m *FacebookIntrest) XXX_Size() int {
	return xxx_messageInfo_FacebookIntrest.Size(m)
}
func (m *FacebookIntrest) XXX_DiscardUnknown() {
	xxx_messageInfo_FacebookIntrest.DiscardUnknown(m)
}

var xxx_messageInfo_FacebookIntrest proto.InternalMessageInfo

func (m *FacebookIntrest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FacebookIntrest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "pb.Item")
	proto.RegisterType((*Status)(nil), "pb.Status")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*FacebookIntrest)(nil), "pb.FacebookIntrest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	Add(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Status, error)
	Read(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	Index(ctx context.Context, in *Empty, opts ...grpc.CallOption) (API_IndexClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Add(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/pb.API/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Read(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/pb.API/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Index(ctx context.Context, in *Empty, opts ...grpc.CallOption) (API_IndexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/pb.API/Index", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIIndexClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_IndexClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type aPIIndexClient struct {
	grpc.ClientStream
}

func (x *aPIIndexClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	Add(context.Context, *Item) (*Status, error)
	Read(context.Context, *Item) (*Item, error)
	Index(*Empty, API_IndexServer) error
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Add(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Read(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Index_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Index(m, &aPIIndexServer{stream})
}

type API_IndexServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type aPIIndexServer struct {
	grpc.ServerStream
}

func (x *aPIIndexServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _API_Add_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _API_Read_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Index",
			Handler:       _API_Index_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keywee.proto",
}

func init() { proto.RegisterFile("keywee.proto", fileDescriptor_keywee_5568685640413dc2) }

var fileDescriptor_keywee_5568685640413dc2 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x51, 0xab, 0xd3, 0x30,
	0x1c, 0xc5, 0x6f, 0x9b, 0xb6, 0xdb, 0xfe, 0xee, 0x5e, 0xaf, 0x7f, 0x45, 0x82, 0x28, 0x94, 0x8a,
	0xd0, 0xa7, 0x21, 0x57, 0xf4, 0xd9, 0x3d, 0x28, 0xf4, 0x4d, 0xba, 0x0f, 0x30, 0xd2, 0xe6, 0xbf,
	0x11, 0xb6, 0x36, 0xa5, 0x49, 0xd1, 0xed, 0x73, 0xf9, 0x01, 0x25, 0x59, 0x2b, 0xdb, 0x7d, 0x3b,
	0xe7, 0x77, 0x20, 0x39, 0xcd, 0x29, 0x2c, 0x0f, 0x74, 0xfa, 0x4d, 0xb4, 0xea, 0x7a, 0x6d, 0x35,
	0x86, 0x5d, 0x95, 0xfd, 0x0d, 0x21, 0x2a, 0x2c, 0x35, 0xf8, 0x00, 0xa1, 0x92, 0x3c, 0x48, 0x83,
	0x7c, 0x51, 0x86, 0x4a, 0xe2, 0x23, 0xb0, 0xa1, 0x3f, 0xf2, 0xd0, 0x03, 0x27, 0xf1, 0x13, 0x3c,
	0x90, 0xb1, 0xaa, 0x11, 0x96, 0xb6, 0x3d, 0x09, 0x79, 0xe2, 0x2c, 0x0d, 0xf2, 0x79, 0x79, 0x3f,
	0xd1, 0xd2, 0x41, 0xfc, 0x08, 0xf7, 0x62, 0x90, 0x4a, 0xb4, 0x35, 0x6d, 0x8d, 0x3a, 0x13, 0x8f,
	0xd2, 0x20, 0x67, 0xe5, 0x72, 0x82, 0x1b, 0x75, 0x26, 0xe4, 0x30, 0xab, 0x75, 0x6b, 0xa9, 0xb5,
	0x3c, 0xf6, 0x37, 0x4c, 0x16, 0xdf, 0x40, 0x6c, 0x95, 0x3d, 0x12, 0x4f, 0x3c, 0xbf, 0x18, 0xcc,
	0x60, 0xa9, 0x5a, 0xdb, 0x6b, 0x39, 0xd4, 0x56, 0xe9, 0x96, 0xcf, 0x7c, 0x78, 0xc3, 0x5c, 0xe3,
	0x3d, 0x69, 0x3e, 0x4f, 0x99, 0x6b, 0xbc, 0x27, 0x8d, 0x6f, 0x21, 0xb1, 0xba, 0x53, 0xb5, 0xe1,
	0x0b, 0x0f, 0x47, 0x87, 0xdf, 0xe1, 0xd5, 0x4e, 0xd4, 0x54, 0x69, 0x7d, 0xd8, 0xba, 0x23, 0xc8,
	0x58, 0xc3, 0x21, 0x65, 0xf9, 0x8b, 0xa7, 0xd7, 0xab, 0xae, 0x5a, 0xfd, 0x1c, 0xc3, 0xe2, 0x92,
	0x95, 0x8f, 0xbb, 0x5b, 0x60, 0xb2, 0x6f, 0x90, 0x6c, 0xac, 0xb0, 0x83, 0x41, 0x84, 0xa8, 0xd6,
	0x92, 0xfc, 0xcb, 0xb1, 0xd2, 0x6b, 0xf7, 0x75, 0x0d, 0x19, 0x23, 0xf6, 0x34, 0xbe, 0xdf, 0x64,
	0xb3, 0x19, 0xc4, 0x3f, 0x9a, 0xce, 0x9e, 0xb2, 0xaf, 0xf0, 0xf2, 0xd9, 0x2d, 0xee, 0xa4, 0x56,
	0x34, 0x34, 0x6e, 0xe0, 0xf5, 0xb8, 0x4a, 0x38, 0xad, 0xf2, 0x24, 0x81, 0xad, 0x7f, 0x15, 0xf8,
	0x01, 0xd8, 0x5a, 0x4a, 0x9c, 0xbb, 0xb2, 0x6e, 0xbd, 0x77, 0xe0, 0xd4, 0xa5, 0x51, 0x76, 0x87,
	0xef, 0x21, 0x72, 0x5b, 0x5c, 0xe5, 0xff, 0x55, 0x76, 0x87, 0x29, 0xc4, 0x45, 0x2b, 0xe9, 0x0f,
	0x2e, 0x1c, 0xf4, 0x75, 0xae, 0xf3, 0xcf, 0x41, 0x95, 0xf8, 0xff, 0xe3, 0xcb, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5e, 0xdf, 0xb9, 0x8e, 0x2f, 0x02, 0x00, 0x00,
}
